name: Build aTFC

on:
  push:
    branches: '**'
  pull_request:
    branches: [ master, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Run build
      run: ./gradlew build
    - name: Run Forge data generator
      uses: nick-invision/retry@v2.4.0
      with:
        command: ./gradlew runData
        timeout_minutes: 5
        max_attempts: 5
        retry_on: error
    - name: Assmble mod-jar
      run: ./gradlew assemble
    - name: Upload mod-jar
      uses: actions/upload-artifact@v2.2.2
      with:
        name: aTFC
        path: build/libs/*.jar
